/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c4c6d4",
        "slate-500": "#64748B",
        "secondary-fixed-dim": "#adc6ff",
        "slate-900": "#0F172A",
        "error": "#ba1a1a",
        "teal-vibrant": "#00BFB3",
        "primary": "#002768",
        "primary-fixed": "#dae2ff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#001a41",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "surface": "#f8f9ff",
        "tertiary-fixed": "#67f8eb",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#00201d",
        "accent-gold": "#FEBB02",
        "surface-tint": "#315ab4",
        "on-secondary-container": "#fefcff",
        "on-primary-fixed-variant": "#0e419b",
        "on-tertiary-fixed-variant": "#00504a",
        "surface-variant": "#d3e4fe",
        "primary-container": "#003b95",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "on-primary-container": "#8cabff",
        "on-primary-fixed": "#001847",
        "inverse-primary": "#b2c5ff",
        "tertiary-container": "#004a45",
        "on-secondary-fixed-variant": "#004494",
        "on-error-container": "#93000a",
        "surface-container-low": "#eff4ff",
        "tertiary": "#00322e",
        "secondary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#43dccf",
        "secondary-container": "#1070e8",
        "primary-fixed-dim": "#b2c5ff",
        "on-tertiary-container": "#0fc2b6",
        "outline": "#747783",
        "surface-container-high": "#dce9ff",
        "on-background": "#0b1c30",
        "surface-dark": "#0F172A",
        "surface-bright": "#f8f9ff",
        "on-surface": "#0b1c30",
        "secondary": "#0058bc",
        "background": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bg": "#FFFFFF",
        "error-container": "#ffdad6",
        "on-surface-variant": "#434652",
        "inverse-surface": "#213145",
        "surface-container": "#e5eeff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "1rem",
        "container-max": "1280px",
        "margin-mobile": "1rem",
        "stack-sm": "0.5rem",
        "margin-desktop": "2.5rem",
        "gutter": "1.5rem",
        "stack-lg": "2rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"]
      }
    }
  },
  plugins: [],
}
